AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless NodeJS Cloud
Resources:
  NodeJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.endpoint
      Runtime: nodejs8.10
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 40
      Events:
        GetRootResource:
          Type: Api
          Properties:
            Path: /
            Method: any
