service: aws-lambda-plain-nodejs-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: handler.endpoint
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
